# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sandeep Parikh
tagline:          'Nerdish leanings'
url:              http://crcsmnky.github.io

paginate:         1

baseurl:          /

author:
  name:           'Sandeep Parikh'
  url:            https://twitter.com/crcsmnky

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/crcsmnky/crcsmnky.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Twitter: 'https://twitter.com/crcsmnky'
